[package]
name = "renderer"
version = "0.1.0"
authors = ["alexbb <hou.alexx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.7.3", features = ["small_rng"]}
threadpool = "1.8.1"
